//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Entities.ServerObjects
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ServerModelChainMS : DbContext
    {
        public ServerModelChainMS()
            : base("name=ServerModelChainMS")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Comment> Comments { get; set; }
        public DbSet<Gallery> Galleries { get; set; }
        public DbSet<GrantPermission> GrantPermissions { get; set; }
        public DbSet<GroupMemberPermission> GroupMemberPermissions { get; set; }
        public DbSet<GroupPermission> GroupPermissions { get; set; }
        public DbSet<Image> Images { get; set; }
        public DbSet<Manufacture> Manufactures { get; set; }
        public DbSet<MenuCategory> MenuCategories { get; set; }
        public DbSet<NameDictionary> NameDictionaries { get; set; }
        public DbSet<News> News { get; set; }
        public DbSet<PermissionDefinition> PermissionDefinitions { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<ProductCategory> ProductCategories { get; set; }
        public DbSet<Rating> Ratings { get; set; }
        public DbSet<SEOContent> SEOContents { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TableLastModified> TableLastModifieds { get; set; }
        public DbSet<TraceChange> TraceChanges { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
