//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Entities.ServerObjects
{
    using System;
    using System.Collections.Generic;
    using CMS.Kernel;

    public partial class TraceChange : IEntity
    {
        public long Id { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.Guid> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<decimal> VersionNumber { get; set; }
        public System.Guid GuidId { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string TableChange { get; set; }
        public string PropertyChange { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public int VersionChange { get; set; }
        public Nullable<System.Guid> GuiIdChange { get; set; }
    }
}
