//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Entities.ClientObjects
{
    using CMS.Kernel;
    using System;
    using System.Collections.Generic;

    public partial class News : IEntity
    {
        public long Id { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.Guid> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<decimal> VersionNumber { get; set; }
        public System.Guid GuidId { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string Title { get; set; }
        public Nullable<System.Guid> MenuId { get; set; }
        public string ImagePath { get; set; }
        public string Description { get; set; }
        public string Content { get; set; }
        public string Tags { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsHot { get; set; }
        public Nullable<int> ViewNumber { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public Nullable<System.DateTime> DateExpired { get; set; }
        public string Link { get; set; }
        public string Discriminator { get; set; }
    }
}
